apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: s3_buckets.ansible-aws.toobox.io
spec:
  group: ansible-aws.toobox.io
  names:
    kind: S3Bucket
    listKind: S3BucketList
    plural: s3_buckets
    singular: s3_bucket
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      type: object
      x-kubernetes-preserve-unknown-fields: true
  versions:
  - name: v1alpha1
    served: true
    storage: true
