apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: kinesis_streams.ansible-aws.toobox.io
spec:
  group: ansible-aws.toobox.io
  names:
    kind: KinesisStream
    listKind: KinesisStreamList
    plural: kinesis_streams
    singular: kinesis_stream
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      type: object
      x-kubernetes-preserve-unknown-fields: true
  versions:
  - name: v1alpha1
    served: true
    storage: true
