apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: sqs_queues.ansible-aws.toobox.io
spec:
  group: ansible-aws.toobox.io
  names:
    kind: SQSQueue
    listKind: SQSQueueList
    plural: sqs_queues
    singular: sqs_queue
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      type: object
      x-kubernetes-preserve-unknown-fields: true
  versions:
  - name: v1alpha1
    served: true
    storage: true
