apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: sns_topics.ansible-aws.toobox.io
spec:
  group: ansible-aws.toobox.io
  names:
    kind: SNSTopic
    listKind: SNSTopicList
    plural: sns_topics
    singular: sns_topic
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      type: object
      x-kubernetes-preserve-unknown-fields: true
  versions:
  - name: v1alpha1
    served: true
    storage: true
