apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: kinesis-streams.ansible-aws.modaoperandi.com
spec:
  group: ansible-aws.modaoperandi.com
  names:
    kind: KinesisStream
    listKind: KinesisStreamList
    plural: kinesis-streams
    singular: kinesis-stream
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      type: object
      x-kubernetes-preserve-unknown-fields: true
  versions:
  - name: v1alpha1
    served: true
    storage: true
