apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: iam-roles.ansible-aws.modaoperandi.com
spec:
  group: ansible-aws.modaoperandi.com
  names:
    kind: IAMRole
    listKind: IAMRoleList
    plural: iam-roles
    singular: iam-role
  scope: Cluster
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      type: object
      x-kubernetes-preserve-unknown-fields: true
  versions:
  - name: v1alpha1
    served: true
    storage: true
