apiVersion: apps/v1
kind: Deployment
metadata:
  name: ansible-aws-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: ansible-aws-operator
  template:
    metadata:
      labels:
        name: ansible-aws-operator
    spec:
      serviceAccountName: ansible-aws-operator
      automountServiceAccountToken: true
      securityContext:
        fsGroup: 65534
      containers:
        - name: ansible
          command:
          - /usr/local/bin/ao-logs
          - /tmp/ansible-operator/runner
          - stdout
          # Replace this with the built image name
          image: 027081542926.dkr.ecr.us-east-1.amazonaws.com/ansible-aws-operator:v0.0.2
          imagePullPolicy: Always
          volumeMounts:
          - mountPath: /tmp/ansible-operator/runner
            name: runner
            readOnly: true
          env:
            - name: OIDC_PROVIDER
              value: "oidc.eks.us-east-1.amazonaws.com/id/2E4F9F831377F6C0E966B99127DC895F"
        - name: operator
          # Replace this with the built image name
          image: 027081542926.dkr.ecr.us-east-1.amazonaws.com/ansible-aws-operator:v0.0.2
          imagePullPolicy: Always
          volumeMounts:
          - mountPath: /tmp/ansible-operator/runner
            name: runner
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "ansible-aws-operator"
            - name: ANSIBLE_GATHERING
              value: explicit
            - name: OIDC_PROVIDER
              value: "oidc.eks.us-east-1.amazonaws.com/id/2E4F9F831377F6C0E966B99127DC895F"
      volumes:
        - name: runner
          emptyDir: {}
