apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ansible-aws-operator.name" . }}
  labels:
    {{- include "ansible-aws-operator.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "ansible-aws-operator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "ansible-aws-operator.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "ansible-aws-operator.name" . }}
      automountServiceAccountToken: true
      containers:
        - name: ansible
          command:
          - /usr/local/bin/ao-logs
          - /tmp/ansible-operator/runner
          - stdout
          image: "{{ .Values.image.repository }}:{{ .Values.image.version }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
          - mountPath: /tmp/ansible-operator/runner
            name: runner
            readOnly: true
          resources:
            {{- toYaml .Values.ansible.resources | nindent 12 }}
        - name: operator
          image: "{{ .Values.image.repository }}:{{ .Values.image.version }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
          - mountPath: /tmp/ansible-operator/runner
            name: runner
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "{{ include "ansible-aws-operator.name" . }}"
            - name: ANSIBLE_GATHERING
              value: explicit
          resources:
            {{- toYaml .Values.operator.resources | nindent 12 }}
      volumes:
        - name: runner
          emptyDir: {}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}


# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: ansible-aws-operator
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       name: ansible-aws-operator
#   template:
#     metadata:
#       labels:
#         name: ansible-aws-operator
#     spec:
#       serviceAccountName: ansible-aws-operator
#       containers:
#         - name: ansible
#           command:
#           - /usr/local/bin/ao-logs
#           - /tmp/ansible-operator/runner
#           - stdout
#           # Replace this with the built image name
#           image: 923133779345.dkr.ecr.us-east-1.amazonaws.com/ansible-aws-operator:v0.0.1
#           imagePullPolicy: Always
#           volumeMounts:
#           - mountPath: /tmp/ansible-operator/runner
#             name: runner
#             readOnly: true
#         - name: operator
#           # Replace this with the built image name
#           image: 923133779345.dkr.ecr.us-east-1.amazonaws.com/ansible-aws-operator:v0.0.1
#           imagePullPolicy: Always
#           volumeMounts:
#           - mountPath: /tmp/ansible-operator/runner
#             name: runner
#           env:
#             - name: WATCH_NAMESPACE
#               valueFrom:
#                 fieldRef:
#                   fieldPath: metadata.namespace
#             - name: POD_NAME
#               valueFrom:
#                 fieldRef:
#                   fieldPath: metadata.name
#             - name: OPERATOR_NAME
#               value: "ansible-aws-operator"
#             - name: ANSIBLE_GATHERING
#               value: explicit
#       volumes:
#         - name: runner
#           emptyDir: {}
